/* controller_client_description.h
   Generated by wsdl2h 1.2.9l from ControllerService.wsdl and typemap.dat
   2010-05-21 16:38:03 GMT
   Copyright (C) 2001-2007 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * urn:ControllerService                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

shawnts = "urn:ControllerService"
ns1 = ""
ns2 = "urn:CommonTypes"

*/

//gsoap ns1   schema namespace:	
//gsoap shawnts schema namespace:	urn:ControllerService
//gsoap ns2   schema namespace:	urn:CommonTypes
//gsoap ns1   schema form:	unqualified
//gsoap shawnts schema form:	unqualified
//gsoap ns2   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:base64Binary".
class xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *options; // NOTE: for DIME and MTOM XOP attachments only
	struct soap *soap;
};


//  Forward declaration of class shawnts__receiveStatus.
class shawnts__receiveStatus;

//  Forward declaration of class shawnts__requestStatus.
class shawnts__requestStatus;

//  Forward declaration of class shawnts__status.
class shawnts__status;

//  Forward declaration of class shawnts__receive.
class shawnts__receive;

//  Forward declaration of class ns2__message.
class ns2__message;

//  Forward declaration of class ns2__textMessage.
class ns2__textMessage;

//  Forward declaration of class ns2__binaryMessage.
class ns2__binaryMessage;

//  Forward declaration of class ns2__getNetwork.
class ns2__getNetwork;

//  Forward declaration of class ns2__getNetworkResponse.
class ns2__getNetworkResponse;

/// "urn:CommonTypes":requestId is a simpleType restriction of xs:string.
typedef char* ns2__requestId;

/// "urn:CommonTypes":messageType is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'ns2__messageType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum ns2__messageType
{
	ns2__messageType__TEXT,	///< xs:string value="TEXT"
	ns2__messageType__BINARY,	///< xs:string value="BINARY"
};

/// "urn:CommonTypes":messageLevel is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'ns2__messageLevel' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum ns2__messageLevel
{
	ns2__messageLevel__TRACE,	///< xs:string value="TRACE"
	ns2__messageLevel__DEBUG,	///< xs:string value="DEBUG"
	ns2__messageLevel__INFO,	///< xs:string value="INFO"
	ns2__messageLevel__WARN,	///< xs:string value="WARN"
	ns2__messageLevel__ERROR,	///< xs:string value="ERROR"
	ns2__messageLevel__FATAL,	///< xs:string value="FATAL"
};

/// "urn:CommonTypes":urn is a simpleType restriction of xs:string.
/// Content pattern is "urn:.*"
typedef char* ns2__urn "urn:.*";

/// "urn:ControllerService":receiveStatus is a complexType.
class shawnts__receiveStatus
{ public:
/// Element status of type "urn:ControllerService":requestStatus.
    shawnts__requestStatus*              status                         1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:ControllerService":requestStatus is a complexType.
class shawnts__requestStatus
{ public:
/// Element requestId of type "urn:CommonTypes":requestId.
    ns2__requestId                       requestId                      1;	///< Required element.
/// Size of array of shawnts__status* is 1..unbounded
    int                                  __sizestatus                  ;
/// Pointer to array of length 1..unbounded
    shawnts__status*                    *status                         1;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:ControllerService":status is a complexType.
class shawnts__status
{ public:
/// Element nodeId of type xs:string.
    char*                                nodeId                         1;	///< Required element.
/// Element value of type xs:int.
    int*                                 value                          0;	///< Optional element.
/// Element msg of type xs:string.
    char*                                msg                            0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:ControllerService":receive is a complexType.
class shawnts__receive
{ public:
/// Element msg of type "urn:CommonTypes":message.
    ns2__message*                        msg                            1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:CommonTypes":message is a complexType.
class ns2__message
{ public:
/// Element sourceNodeId of type xs:string.
    char*                                sourceNodeId                   1;	///< Required element.
/// Element timestamp of type xs:dateTime.
    time_t                               timestamp                      1;	///< Required element.
/// CHOICE OF ELEMENTS FOR choice
    int                                  __union_message               ;	///< Union _ns2__union_message selector: set to SOAP_UNION__ns2__union_message_<fieldname>
    union _ns2__union_message
    {
/// Element textMessage of type "urn:CommonTypes":textMessage.
    ns2__textMessage*                    textMessage                    1;	///< Required element.
/// Element binaryMessage of type "urn:CommonTypes":binaryMessage.
    ns2__binaryMessage*                  binaryMessage                  1;	///< Required element.
    }                                    union_message                 ;
//  END OF CHOICE
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:CommonTypes":textMessage is a complexType.
class ns2__textMessage
{ public:
/// Element msg of type xs:string.
    char*                                msg                            1;	///< Required element.
/// Element messageLevel of type "urn:CommonTypes":messageLevel.
    enum ns2__messageLevel*              messageLevel                   0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:CommonTypes":binaryMessage is a complexType.
class ns2__binaryMessage
{ public:
/// Element binaryData of type xs:base64Binary.
    xsd__base64Binary                    binaryData                     1;	///< Required element.
/// Element binaryType of type xs:byte.
    short*                               binaryType                     0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:CommonTypes":getNetwork is a complexType.
class ns2__getNetwork
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:CommonTypes":getNetworkResponse is a complexType.
class ns2__getNetworkResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// Element "urn:ControllerService":receive of type "urn:ControllerService":receive.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:ControllerService":receiveStatus of type "urn:ControllerService":receiveStatus.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:ControllerService":requestStatus of type "urn:ControllerService":requestStatus.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:CommonTypes":getNetwork of type "urn:CommonTypes":getNetwork.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:CommonTypes":getNetworkResponse of type "urn:CommonTypes":getNetworkResponse.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:CommonTypes":message of type "urn:CommonTypes":message.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "urn:CommonTypes":urn of type "urn:CommonTypes":urn.
/// Note: use wsdl2h option -g to generate this global element declaration.

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap shawnts service name:	ControllerPortBinding 
//gsoap shawnts service type:	Controller 
//gsoap shawnts service port:	REPLACE_WITH_ACTUAL_URL 
//gsoap shawnts service namespace:	urn:ControllerService 
//gsoap shawnts service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage ControllerService Definitions

@section ControllerService_bindings Bindings
  - @ref ControllerPortBinding

*/

/**

@page ControllerPortBinding Binding "ControllerPortBinding"

@section ControllerPortBinding_operations Operations of Binding  "ControllerPortBinding"
  - @ref __shawnts__receive
  - @ref __shawnts__receiveStatus

@section ControllerPortBinding_ports Endpoints of Binding  "ControllerPortBinding"
  - REPLACE_WITH_ACTUAL_URL

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * ControllerPortBinding                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __shawnts__receive                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__shawnts__receive" of service binding "ControllerPortBinding"

/**

Operation details:


  - One-way message
  - SOAP document/literal style

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___shawnts__receive(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    shawnts__receive*                   shawnts__receive_,
    // response parameters:
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __shawnts__receive(
    struct soap *soap,
    // request parameters:
    shawnts__receive*                   shawnts__receive_,
    // response parameters:
  );
@endcode

C++ proxy class (defined in soapControllerPortBindingProxy.h):
  class ControllerPortBinding;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap shawnts service method-style:	receive document
//gsoap shawnts service method-encoding:	receive literal
//gsoap shawnts service method-action:	receive ""
int __shawnts__receive(
    shawnts__receive*                   shawnts__receive_,	///< Request parameter
    void	///< One-way message: no response parameter
);

/******************************************************************************\
 *                                                                            *
 * __shawnts__receiveStatus                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "__shawnts__receiveStatus" of service binding "ControllerPortBinding"

/**

Operation details:

  - One-way message
  - SOAP document/literal style

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___shawnts__receiveStatus(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    shawnts__receiveStatus*             shawnts__receiveStatus_,
    // response parameters:
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __shawnts__receiveStatus(
    struct soap *soap,
    // request parameters:
    shawnts__receiveStatus*             shawnts__receiveStatus_,
    // response parameters:
  );
@endcode

C++ proxy class (defined in soapControllerPortBindingProxy.h):
  class ControllerPortBinding;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap shawnts service method-style:	receiveStatus document
//gsoap shawnts service method-encoding:	receiveStatus literal
//gsoap shawnts service method-action:	receiveStatus ""
int __shawnts__receiveStatus(
    shawnts__receiveStatus*             shawnts__receiveStatus_,	///< Request parameter
    void	///< One-way message: no response parameter
);

/* End of controller_client_description.h */
